version: '3'
services:
  server1:
     build: .
     env_file: .env
     container_name: ssh_server1
     ports:
        - "753:53"
        - "722:22"

  server2:
     build: .
     env_file: .env
     container_name: ssh_server2
     ports:
        - "853:53"
        - "822:22"

#  web:
#    image: centos/httpd-24-centos7
#    container_name: httpd
#    user: root
#    ports:
#      - "780:80"
#      - "7443:443"
    
    #volumes:
#      - ./conf/httpd.conf:/etc/httpd/conf/httpd.conf
   #   - /home/lyonel/Documentos/TEST/:/var/www/html/
